### ISSUE TITLE
返回JSON结果格式化失败问题

### ISSUE THREAD

**Issue by Suzichen** [vicanso/cyberapi#10]
版本号V0.1.4 for windows zh-CN

返回的JSON结果未被正确格式化
![Snipaste_2022-12-20_22-18-19](https://user-images.githubusercontent.com/29473565/208688658-4730d772-5994-4a09-bcc4-0bff81458c04.png)

另外在MAC版上，如果返回的数据结果比较复杂，也会出现这个情况，应该是特殊符号转义有问题

期望：能正确格式化JSON结果，展现为树形结构

**Comment by vicanso** [comment]
@Suzichen 我在windows的机器上尝试了也是正常的。麻烦帮忙确认一下响应数据的Content-Type，cyberapi现在的处理是基于响应类型来判断是否以json形式展示。

<img width="330" alt="image" src="https://user-images.githubusercontent.com/437351/208889068-637e80a7-da03-4e5c-93b0-8108937cac08.png">

如果响应类型正确，麻烦提供`应用设置->应用信息`中的所有数据

**Comment by Suzichen** [comment]
> @Suzichen 我在windows的机器上尝试了也是正常的。麻烦帮忙确认一下响应数据的Content-Type，cyberapi现在的处理是基于响应类型来判断是否以json形式展示。
> 
> <img alt="image" width="330" src="https://user-images.githubusercontent.com/437351/208889068-637e80a7-da03-4e5c-93b0-8108937cac08.png">
> 
> 如果响应类型正确，麻烦提供`应用设置->应用信息`中的所有数据，以及mac版本较为复杂的数据的场景。

感谢回复！经测试确实是因为部分项目接口的 Content-Type 没有设置为 application/json 。现在已经可以愉快使用了！
