### ISSUE TITLE
cyberapi.app website not working

### ISSUE THREAD

**Issue by progzone122** [vicanso/cyberapi#18]
![изображение](https://github.com/vicanso/cyberapi/assets/80642969/685a975b-a634-4597-8ac8-c3a05ec02520)

Connection attempt failed

An error occurred while connecting to cyberapi.app.

    The site may be temporarily unavailable or overloaded with requests. Wait a while and try again.
    If you cannot load a single page, check your Internet connection settings.
    If your computer or network is protected by a firewall or proxy server, make sure Firefox is allowed to access the Internet.

**Comment by vicanso** [comment]
I am so sorry, the server has expired. If you need to download the application, please download it from [release page](https://github.com/vicanso/cyberapi/releases).

**Comment by progzone122** [comment]
> I am so sorry, the server has expired. If you need to download the application, please download it from [release page](https://github.com/vicanso/cyberapi/releases).

Then please remove the mention of the website from the readme so that there is no unnecessary confusion =)

**Comment by progzone122** [comment]
thx ❤️
