### ISSUE TITLE
跨域问题的处理方法？

### ISSUE THREAD

**Issue by liudonghua123** [vicanso/cyberapi#2]
这个应用应该是web方式运行的，使用tauri打包，和 http://hoppscotch.io/ （postwoman前身）相同的技术吧，那是怎么解决HTTP(s) API的跨域问题的呢？

hoppscotch 是使用http代理（官方 https://github.com/hoppscotch/proxyscotch 或自己搭建的）或者Browser Extension方式实现跨域的。

我自己也使用tauri封装了一下hoppscotch，跨域是通过tauri的http原生模块实现的。https://github.com/liudonghua123/hoppscotch-app

**Comment by vicanso** [comment]
我未直接在浏览器发送http(s)请求，都是通过js与rust的方式，rust来发送请求。tauri也直接封装了reqwest的方法给浏览器使用，基于安全的考虑，需要在项目配置中指定允许访问的域名即可
