### ISSUE TITLE
有考虑过隐藏标题吗或者重写一个标题。

### ISSUE THREAD

**Issue by the-pawn-2017** [vicanso/cyberapi#32]
UI挺好看的，一眼naive-UI。
就是标题有点不好看，去掉会不会更好？
![图片](https://github.com/vicanso/cyberapi/assets/115976311/a5ea3ca4-959e-436c-9457-e5b564d39fa4)

**Comment by vicanso** [comment]
标题是指哪一部分呢？ File Edit Window 这部分？

**Comment by the-pawn-2017** [comment]
> 标题是指哪一部分呢？ File Edit Window 这部分？

是啊

**Comment by vicanso** [comment]
尝试一下最新的版本，windows系统已处理
