### ISSUE TITLE
设置的Header不生效问题

### ISSUE THREAD

**Issue by youaodu** [vicanso/cyberapi#38]
软件版本：v0.1.20，v0.1.19
操作系统：win10企业版
CPU：intel I5
问题：我在Header中设置了一个值，软件刚打开第一次发送请求，这个header有携带。但是后续的请求不携带。
![image](https://github.com/vicanso/cyberapi/assets/49941556/d2936033-fdb7-49f2-ac54-e147ef325eb3)

**Comment by vicanso** [comment]
<img width="169" alt="image" src="https://github.com/vicanso/cyberapi/assets/437351/9cabe032-71f1-46ea-a159-088aa414e83a">
Cookie 直接在此设置即可，会使用Cookie中有的值
