### ISSUE TITLE
环境变量用法？

### ISSUE THREAD

**Issue by kuyoonjo** [vicanso/cyberapi#5]
嗨，这个环境变量怎么用呀？

**Comment by vicanso** [comment]
@kuyoonjo  环境变量一般用于接口测试时对接不同的环境，例如tiny服务正式环境是`https://tiny.npmtrend.com`，测试环境是`http://127.0.0.1:3000`，则可配置如下（测试与正式名称一致，正式环境未勾选生效）：

<img width="841" alt="image" src="https://user-images.githubusercontent.com/437351/198576756-0d366b25-23fa-45a5-9dbe-318cfe09d1f7.png">
之后配置请求时可勾选对应的环境变量，填写请求path部分即可：

<img width="563" alt="image" src="https://user-images.githubusercontent.com/437351/198576988-0a321d9a-3bb6-43b0-82e7-e971276dac7c.png">

当需要切换环境时，勾选生产环境生效，取消本地开发环境即可
